name: givefit
description: GiveFit
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  google_fonts: ^0.2.0
  intl: 0.16.0
  provider: 4.0.5
  connectivity: ^0.4.3+2
  dio: 3.0.8
  shared_preferences:
  pedantic: ^1.8.0
  image_picker: ^0.6.3+1
  permission_handler: ^4.2.0+hotfix.2
  youtube_player_flutter:
  firebase_auth:
  google_sign_in:
  device_id:
  flutter_facebook_login:
  http:
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/